version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login --no-include-email --region eu-north-1 | docker login --username AWS --password-stdin 643080207297.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ecr-repo:latest .

  post_build:
    commands:
      - echo "Tagging Docker image..."
      - docker tag 643080207297.dkr.ecr.eu-north-1.amazonaws.com/ecr-repo
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 643080207297.dkr.ecr.eu-north-1.amazonaws.com/ecr-repo
