phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ecr-repo:2.3 .

  post_build:
    commands:
      - echo "Tagging Docker image..."
      - docker tag ecr-repo:2.3 590183710695.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:2.3
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 590183710695.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:2.3

artifacts:
  files:
    - '**/*'
